version: "3.8"

services:

  docker_spring_boot:
    container_name: openjdk17
    build:
      context: .
      dockerfile: Dockerfile



    image: block10-docker:1
    ports:
      - "8080:8080"
    networks:
      - bosonit-network

  postgres_db:
    container_name: postgresTest
    links:
      - "docker_spring_boot"
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=usuario
      - POSTGRES_DB=person
    ports:
        - "5432:5432"
    networks:
      - bosonit-network

  pgadmin_web:
    container_name: pgadmin_web

    image: dpage/pgadmin4

    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "80:80"
    depends_on:
      - postgres_db
    networks:
      - bosonit-network



networks:
  bosonit-network:
    driver: bridge



